name: Flutter Mobile CI

on:
  push:
    branches: [ "main" ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Instalar dependencias
        run: flutter pub get

      - name: Linter y Análisis Estático
        run: flutter analyze

      - name: Pruebas Unitarias
        run: flutter test

      - name: Análisis de SonarQube / SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Notificar a Discord en caso de fallo
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content": "🚨 **¡Alerta en el Pipeline de RentaFácil!** La integración continua ha fallado en la ejecución. Revisa los logs del repositorio."}' \
          ${{ secrets.DISCORD_WEBHOOK }}