name: Flutter Mobile CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Instalar dependencias
        run: cd app_inmobiliaria && flutter pub get

      - name: Linter y Análisis Estático
        run: cd app_inmobiliaria && flutter analyze

      - name: Pruebas Unitarias
        run: cd app_inmobiliaria && flutter test
